### ISSUE TITLE
appimage of these five apps

### ISSUE THREAD

**Issue by zaxebo1** [probonopd/AppImageKit#243]
Yesterday only, i discovered appimage. I am really excited.
The following utilities which I use extensively, are not in the appimage gallery of apps. 
Can - providing of these five apps/apps-recipe - be kindly added to the roadmap :

VVIMP:  **cryptsetup,  latexmk (including the entire texlive), emacs**

OPTIONAL: dia, jabref (should include the entire openjdk contained in itself)

**Comment by PHPJosh** [comment]
in about a month or so i will be making alot of appimages of apps there are none for as I am make an OS centered around AppImageKit and will need as much software available to end users as possible and will maintain which ever ones i make until there are other maintainers or the Upstream developers start making appimages (which is what i am hoping for) I will add what ever ones i do make to the Appimage repo

**Comment by zaxebo1** [comment]
thanks.
judging with the level of happiness i have with AppImage downloads i made today, probably i forsee myself as **maintainer** of some appimages **in future**    :-) 

but, may be i will try going through docs for making AppImage **myself** in november, when i will have lots of time to invest for some learning.

**Comment by probonopd** [comment]
Although I do some sample apps on Bintray, I don't have the time to package every application on earth. Hence I kindly ask you to send AppImage packaging requests to the upstream authors of the respective software. 

Another way to get AppImages is to convert deb ingredients to AppImage. I am working on making this much easier. How would you like maintaining something like

```
app: Lantern

ingredients:
  dist: trusty
  sources: 
    - deb http://archive.ubuntu.com/ubuntu/ trusty main universe
  debs:
    - https://s3.amazonaws.com/lantern/lantern-installer-beta-64-bit.deb
```

and get a working, up-to-date, AppImage?
