### ISSUE TITLE
Can't load or found qt platform plugin 'xcb'

### ISSUE THREAD

**Issue by caoli5288** [probonopd/AppImageKit#360]
A Qt5 based app packaged on ubuntu14.04 can not run on fedora25. It says.
> Can't load or found qt platform plugin 'xcb'

How to?

**Comment by caoli5288** [comment]
All lib copied list here
```
# ls ./usr/lib
libasyncns.so.0       libfreetype.so.6     libnsl.so.1             libplds4.so            libQt5Xml.so.5     libxcb-dri3.so.0     libXfixes.so.3
libatk-1.0.so.0       libgcrypt.so.11      libnspr4.so             libpng12.so.0          libsmime3.so       libxcb-glx.so.0      libXinerama.so.1
libavahi-client.so.3  libglapi.so.0        libnss3.so              libpulsecommon-4.0.so  libsndfile.so.1    libxcb-present.so.0  libXi.so.6
libavahi-common.so.3  libgmodule-2.0.so.0  libnssutil3.so          libpulse.so.0          libtasn1.so.6      libxcb-render.so.0   libXrandr.so.2
libcairo.so.2         libgnutls.so.26      libogg.so.0             libQt5Core.so.5        libthai.so.0       libxcb-shm.so.0      libXrender.so.1
libcef.so             libgraphite2.so.3    libpango-1.0.so.0       libQt5DBus.so.5        libvorbisenc.so.2  libxcb-sync.so.1     libxshmfence.so.1
libcups.so.2          libharfbuzz.so.0     libpangocairo-1.0.so.0  libQt5Gui.so.5         libvorbis.so.0     libXcomposite.so.1   libXss.so.1
libdatrie.so.1        libicudata.so.52     libpangoft2-1.0.so.0    libQt5Multimedia.so.5  libwrap.so.0       libXcursor.so.1      libXtst.so.6
libdbus-1.so.3        libicui18n.so.52     libpcre.so.3            libQt5Network.so.5     libX11-xcb.so.1    libXdamage.so.1      libXxf86vm.so.1
libffi.so.6           libicuuc.so.52       libpixman-1.so.0        libQt5Widgets.so.5     libXau.so.6        libXdmcp.so.6
libFLAC.so.8          libjson-c.so.2       libplc4.so              libQt5X11Extras.so.5   libxcb-dri2.so.0   libXext.so.6
```

**Comment by probonopd** [comment]
Hi @caoli5288 please provide a download link to the AppImage or AppDir.

**Comment by caoli5288** [comment]
@probonopd Sure. I upload it to [MEGA](https://mega.nz/#!CJgGkbxS!fO4dGH2FCBe3dmSJQTOL7YUqxtZRqIJHZS_TB3OltFE).
And the deb file [here](http://s1.music.126.net/download/pc/netease-cloud-music_1.0.0_amd64_ubuntu14.04.deb).
Hope useful. THX.

**Comment by probonopd** [comment]
@caoli5288 how did you produce the AppImage?

**Comment by probonopd** [comment]
This yml file generates a working AppImage for me. But the application is all Chinese, I don't understand a single word. Can it be switched to English?

```
app: netease-cloud-music
binpatch: true

ingredients:
  dist: trusty
  packages:
    - netease-cloud-music
  sources: 
    - deb http://archive.ubuntu.com/ubuntu/ trusty main universe
    - deb http://archive.ubuntu.com/ubuntu/ trusty-updates main universe
    - deb http://archive.ubuntu.com/ubuntu/ trusty-security main universe
  script:
    - URL="http://s1.music.126.net/download/pc/netease-cloud-music_1.0.0_amd64_ubuntu14.04.deb"
    - echo "$URL" | cut -d "_" -f 2 > VERSION
    - wget -c "$URL"
    - wget -c "http://security.ubuntu.com/ubuntu/pool/main/n/nss/libnss3_3.26.2-0ubuntu0.14.04.3_amd64.deb"

script:
  - cp ./usr/share/icons/hicolor/scalable/apps/netease-cloud-music.svg .
  - sed -i -e 's|cd |# cd |g' usr/bin/netease-cloud-music
  - mv usr/lib/x86_64-linux-gnu/nss/* usr/lib/x86_64-linux-gnu/
```
